#!/usr/bin/env bash
# validate.sh — run all available static checks on configs and scripts.
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
ERRORS=0

check() {
  if command -v "$1" &>/dev/null; then
    return 0
  else
    echo "SKIP: $1 not installed"
    return 1
  fi
}

echo "=== shellcheck ==="
if check shellcheck; then
  while IFS= read -r -d '' script; do
    echo "  checking $script"
    shellcheck -e SC1091 "$script" || ERRORS=$((ERRORS + 1))
  done < <(find "$ROOT/scripts" "$ROOT/config/butane/files" -name "*.sh" -print0)
fi

echo ""
echo "=== systemd-analyze verify ==="
if check systemd-analyze; then
  UNIT_DIR="$ROOT/config/butane/files/systemd"
  # The state mount unit is not here: it is generated by Butane from
  # storage.filesystems (with_mount_unit) and checked in the rendered Ignition
  # by test-render.sh instead.
  #
  # Every hand-written unit in one pass: no two share a name, so they can all
  # be loaded together.
  # No '*.conf': every .conf under here is a dropin fragment, and
  # systemd-analyze cannot verify one on its own — it rejects the filename
  # outright, since a fragment is not a unit. Dropins are covered by the render
  # (Butane --strict) and by the mock VM boot instead.
  mapfile -t units < <(find "$UNIT_DIR" -type f \
    \( -name '*.service' -o -name '*.mount' -o -name '*.socket' -o -name '*.timer' \))
  # The exit code carries no signal: it is 1 even on a clean tree, because the
  # ExecStart binaries live on the server and var-mnt-state.mount is generated
  # by Butane. A real typo is only a WARNING, so the text is all there is.
  # Filter out exactly that expected noise and fail on whatever is left — an
  # allowlist of bad strings would silently pass everything the day systemd
  # rewords a diagnostic.
  out="$(systemd-analyze verify "${units[@]}" 2>&1 || true)"
  bad="$(printf '%s\n' "$out" | grep -vE \
    'is not executable:|Unit var-mnt-state\.mount not found|^$' || true)"
  if [[ -n "$bad" ]]; then
    echo "  unexpected systemd-analyze output:"
    printf '%s\n' "$bad" | sed 's/^/    /'
    ERRORS=$((ERRORS + 1))
  else
    echo "  OK (${#units[@]} units)"
  fi
fi

echo ""
echo "=== butane merge + render + per-env assertions ==="
if check podman; then
  if bash "$ROOT/scripts/test-render.sh"; then
    echo "    OK"
  else
    echo "    FAIL"; ERRORS=$((ERRORS + 1))
  fi
fi

echo ""
echo "=== admin UI server ==="
if bash "$ROOT/scripts/test-pbweb.sh"; then
  echo "    OK"
else
  echo "    FAIL"; ERRORS=$((ERRORS + 1))
fi

echo ""
if [[ "$ERRORS" -eq 0 ]]; then
  echo "All checks passed."
else
  echo "ERRORS: $ERRORS check(s) failed." >&2
  exit 1
fi
